### PR TITLE
Update sources.bib

### PR DESCRIPTION
**Pull request by louplum**
Beard sources update as of May 21, 2023 - additional Cariban and Tupian language entries for input to Kinbank

### CODE REVIEW

**Comment by louplum** [comment]
Email me at abeard@unm.edu with questions/concerns. - AB

**Comment by SamPassmore** [comment]
Hi A. Beard,

This commit just adds six new sources. Do you plan to add data that links to these sources? Or are these sources corrections? In this case, you will need to delete what these sources are replacing. 

Sam.

**Comment by louplum** [comment]
Hi Sam,

I was attempting to add the sources corresponding with new language data files I uploaded onto Kinbank. I am new to GitHub, so I am sure I didn’t do it correctly :/

Sorry about that! I have a Sharepoint with Joshua so I’ll add the files and source data there so he has the newest data to upload to Kinbank.

Thanks,
:)
Ashley Beard

From: SamPassmore ***@***.***>
Date: Sunday, May 21, 2023 at 6:46 PM
To: kinbank/goeldi ***@***.***>
Cc: Ashley Beard ***@***.***>, Author ***@***.***>
Subject: Re: [kinbank/goeldi] Update sources.bib (PR #10)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
  [EXTERNAL]

Hi A. Beard,

This commit just adds six new sources. Do you plan to add data that links to these sources? Or are these sources corrections? In this case, you will need to delete what these sources are replacing.

Sam.

**Comment by SamPassmore** [comment]
No worries. Git can be a steep learning curve - but I promise it has long-term benefits! 
Are you saying you have previously uploaded new data to this dataset (and I missed that merge request)? Or that you were expecting both data and sources to be uploaded at the same time?

Git will automatically track changes to old files (e.g. sources.bib) but you need to explicitly tell it to track new files (with git add). Let me know if a zoom call would be helpful (although I will be on holiday from Friday).

**Comment by louplum** [comment]
Hi Sam,

I uploaded the data files at the same time as updating the sources.bib, but I sent that to Joshua’s fork of the repository so that he could look them over first. The main kinbank path is where I sent the sources update. Those sources are for the data files I sent to Joshua.
:)
Ashley Beard

From: SamPassmore ***@***.***>
Date: Sunday, May 21, 2023 at 6:57 PM
To: kinbank/goeldi ***@***.***>
Cc: Ashley Beard ***@***.***>, Author ***@***.***>
Subject: Re: [kinbank/goeldi] Update sources.bib (PR #10)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
  [EXTERNAL]

No worries. Git can be a steep learning curve - but I promise it has long-term benefits!
Are you saying you have previously uploaded new data to this dataset (and I missed that merge request)? Or that you were expecting both data and sources to be uploaded at the same time?

Git will automatically track changes to old files (e.g. sources.bib) but you need to explicitly tell it to track new files (with git add). Let me know if a zoom call would be helpful (although I will be on holiday from Friday).

**Comment by SamPassmore** [comment]
Ok. No problem. I see you also have your own fork. 

My advice would be to do this kind of thing in branches within this repository because it keeps all the discussions about this dataset in one place. Rather than creating copies of the repository with forks, which makes it harder to track the divergence of datasets. This is ultimately Josh's call, though. 

Once Josh has checked over the files, maybe we can all have a call to make sure the pipeline works for you guys. 
(But I am going on holiday on Friday for 2 weeks, so no rush). 

Sam

**Review by jtbirchall — CHANGES_REQUESTED** [review]
Please include all authors in Ferreira-Alves et al. (2019) in the author field (instead of et al.) and correct name.  Nogueira et al. is missing additional authors. 

Include full publisher name for Riviere. Also include place field.

**Comment by louplum** [comment]
Hi Ashley and Sam,

Sam, thanks for following up on this. I looked at the discussion on the PR and just posted a review.

Ashley, could you please make the changes to sources.bib I suggested in the review? I didn't get a pull request on my fork of the project for the data. I think Sam's suggestion to keep everything as branches on the main repo is a good idea. This repo should only have the Tupian and Cariban data. We'll have to work out a plan for the sign language data later.

I'm going to be traveling from next weekend through much of summer.  It may take a little while for me to review anything pushed after the next few days, but I'll try to keep on top of things.


Joshua Birchall
Visiting Assistant Professor
Department of Linguistics
University of New Mexico
________________________________

**Comment by SamPassmore** [comment]
Hi Ashely / Josh. 

I merged the most recent request, but I've seen now there are two other requests for changes on the sources file. 
Do all of these need to be merged or just the latest?

Ideally, we would just update on one branch so we dont have duplicate pull requests.

If they are all changes for the same thing, then I will close the remaining two requests.

**Comment by louplum** [comment]
Hi Sam,

The sources updates I added were followed by a couple requests from Josh to fix errors in the updates (removing Roman numerals from some entries, and then adding address and source ID information to entries).

I updated these separately upon becoming aware of the requests, making a pull request on each to alert Josh that the updates had been corrected. I think the duplicate requests are my doing, and as such can be closed.
:)
Ashley Beard
________________________________

**Pull request closed without merging**
